{
 "title": "Request Type Queries",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "Total Request", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total requests across all models",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(traces_spanmetrics_calls_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Models by Request Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (span_name) (increase(traces_spanmetrics_calls_total[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true
  },
  { "title": "Chat Completion Request", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Traces with response model recorded",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "limit": 20,
     "query": "{span.ai.request_type = \"chat_completion\"}",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Request Made by Chat Completion",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "limit": 20,
     "query": "{span.ai.request_type = \"chat_completion\"}",
     "tableType": "traces"
    }
   ]
  },
  { "title": "Latency Per Model", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "P50 latency per model (approximate)",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (span_name, le) (rate(traces_spanmetrics_latency_bucket[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P95 latency per model (Mean)",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (span_name, le) (rate(traces_spanmetrics_latency_bucket[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true
  }
 ]
}