{
 "title": "FastAPI Dashboard",
 "time": { "from": "now-3m", "to": "now" },
 "refresh": "3s",
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[5m]))"
    }
   ]
  },
  {
   "title": "Request per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status_code) (rate(http_requests_total[5m]))",
     "legendFormat": "{{ status_code }}"
    }
   ]
  },
  {
   "title": "Errors per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status_code=~\"5..\"}[5m]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Total Requests Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "rate(http_requests_total[5m])", "legendFormat": "{{ method }} {{ path }}" }
   ]
  },
  {
   "title": "Average response time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 15, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(fastapi_requests_duration_seconds_sum[5m]) / rate(fastapi_requests_duration_seconds_count[5m])",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Request Duration [s] - p60",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.60, rate(fastapi_requests_duration_seconds_bucket[5m]))",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[5m]) * 100",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes / 1024 / 1024",
     "legendFormat": "mem"
    }
   ]
  },
  {
   "title": "Logger Stream",
   "type": "logs",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "{service=\"gatewayz-api\"}"
    }
   ]
  }
 ]
}